# Support Vector Regression with Insurance Dataset(SVR)

## Importing the Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [7]:
dataset = pd.read_csv('Health_insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Encoding the datas

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 19 27.9 0]
 [0.0 1.0 1.0 ... 18 33.77 1]
 [0.0 1.0 1.0 ... 28 33.0 3]
 ...
 [1.0 0.0 1.0 ... 18 36.85 0]
 [1.0 0.0 1.0 ... 21 25.8 0]
 [1.0 0.0 0.0 ... 61 29.07 0]]


## Splitting the dataset

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature scaling

In [11]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import  StandardScaler 
column_trans = ColumnTransformer(
    [('scaler', StandardScaler(),[8,9,10])],
    remainder='passthrough') 
X_train = column_trans.fit_transform(X_train)
X_test =column_trans.fit_transform(X_test)

## Training the dataset

In [12]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train,y_train)

SVR()

## Predicting the results

In [13]:
y_pred=regressor.predict(X_test)

In [14]:
print(y_pred)

[9446.51971212 9419.74816413 9466.34654717 9475.5542417  9437.04270819
 9384.97973288 9348.86018949 9452.88529283 9404.92361666 9390.54166309
 9408.19908712 9436.40839297 9397.86416891 9366.22603785 9413.98618748
 9440.60377015 9470.40374911 9355.89850898 9387.01301341 9412.51453743
 9471.43019604 9468.48324768 9458.34092364 9464.11151041 9352.81294362
 9387.55260467 9391.066622   9413.62079777 9356.64790085 9418.91409724
 9409.53443609 9480.80544581 9478.7785333  9462.02600478 9417.6749564
 9358.68921024 9433.07076972 9425.68265211 9450.7675431  9346.0294036
 9395.33504495 9353.10943427 9447.05954926 9487.32112679 9410.85456116
 9355.45608687 9440.24169905 9395.33947208 9368.50975334 9459.43283722
 9359.467643   9378.17060501 9469.5056026  9473.54353565 9462.77458895
 9373.79556458 9362.08726957 9437.63787738 9434.57109629 9469.89007602
 9343.63005689 9484.07856061 9469.98922616 9440.25162602 9446.88924063
 9449.45096118 9408.53241754 9439.52962136 9368.96737757 9426.55514389
 9478.61